name: housing_submarket
channels:
  - conda-forge
  - pip
packages:
  - pandas
  - seaborn
  - conda-forge:
    - matplotlib
  - pip:
    - black
    - openpyxl
    - scikit-learn
    - scikit-learn-extra
dependencies:
  - python = 3.9*