name: housing_submarket
channels:
  - conda-forge
  - pip
packages:
  - pandas
  - seaborn
  - psycopg2
  - sqlalchemy
  - seaborn
  - conda-forge:
    - matplotlib
    - geopandas
    - pyproj
    - python-dotenv
  - pip:
    - black
    - openpyxl
    - scikit-learn
    - scikit-learn-extra
    - python-dotenv
dependencies:
  - python = 3.9*