CREATE FOREIGN TABLE ipd_2021 (
        objectid int4, 
        geoid20 varchar(80), 
        statefp20 varchar(80), 
        countyfp20 varchar(80), 
        name20 varchar(80), 
        d_class varchar(80), 
        d_cntest numeric(38, 8), 
        d_cntmoe numeric(38, 8), 
        d_pctest numeric(38, 8), 
        d_pctile numeric(38, 8), 
        d_pctmoe numeric(38, 8), 
        d_score numeric(38, 8), 
        em_class varchar(80), 
        em_cntest numeric(38, 8), 
        em_cntmoe numeric(38, 8), 
        em_pctest numeric(38, 8), 
        em_pctile numeric(38, 8), 
        em_pctmoe numeric(38, 8), 
        em_score numeric(38, 8), 
        f_class varchar(80), 
        f_cntest numeric(38, 8), 
        f_cntmoe numeric(38, 8), 
        f_pctest numeric(38, 8), 
        f_pctile numeric(38, 8), 
        f_pctmoe numeric(38, 8), 
        f_score numeric(38, 8), 
        fb_class varchar(80), 
        fb_cntest numeric(38, 8), 
        fb_cntmoe numeric(38, 8), 
        fb_pctest numeric(38, 8), 
        fb_pctile numeric(38, 8), 
        fb_pctmoe numeric(38, 8), 
        fb_score numeric(38, 8), 
        lep_class varchar(80), 
        lep_cntest numeric(38, 8), 
        lep_cntmoe numeric(38, 8), 
        lep_pctest numeric(38, 8), 
        lep_pctile numeric(38, 8), 
        lep_pctmoe numeric(38, 8), 
        lep_score numeric(38, 8), 
        li_clas varchar(80), 
        li_cntest numeric(38, 8), 
        li_cntmoe numeric(38, 8), 
        li_pctest numeric(38, 8), 
        li_pctile numeric(38, 8), 
        li_pctmoe numeric(38, 8), 
        li_score numeric(38, 8), 
        oa_class varchar(80),
        oa_cntest numeric(38, 8), 
        oa_cntmoe numeric(38, 8), 
        oa_pctest numeric(38, 8), 
        oa_pctile numeric(38, 8), 
        oa_pctmoe numeric(38, 8), 
        oa_score numeric(38, 8), 
        rm_class varchar(80), 
        rm_cntest numeric(38, 8), 
        rm_cntmoe numeric(38, 8), 
        rm_pctest numeric(38, 8), 
        rm_pctile numeric(38, 8), 
        rm_pctmoe numeric(38, 8), 
        rm_score numeric(38, 8), 
        y_class varchar(80), 
        y_cntest numeric(38, 8), 
        y_cntmoe numeric(38, 8), 
        y_pctest numeric(38, 8), 
        y_pctile numeric(38, 8), 
        y_pctmoe numeric(38, 8), 
        y_score numeric(38, 8), 
        ipd_score numeric(38, 8), 
        u_tpopest numeric(38, 8), 
        u_tpopmoe numeric(38, 8), 
        u_pop6est numeric(38, 8), 
        u_pop6moe numeric(38, 8), 
        u_ppovest numeric(38, 8), 
        u_ppovmoe numeric(38, 8), 
        u_pnicest numeric(38, 8), 
        u_pnicmoe numeric(38, 8), 
        namelsad varchar(80), 
        mun1 varchar(35), 
        mun2 varchar(35), 
        mun3 varchar(35), 
        co_name varchar(35), 
        state varchar(2), 
        gdb_geomattr_data bytea, 
        shape geometry

)
        SERVER foreign_server
        OPTIONS (schema_name 'demographics', table_name 'ipd_2021');